FROM node:20-alpine

WORKDIR /app

# Next.js'in Docker dışından erişilebilmesi için gerekli ortam değişkeni
ENV HOSTNAME="0.0.0.0"

# Cache package dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy source code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]